// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/endpoints/delete.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEndpointDeleter is a mock of EndpointDeleter interface.
type MockEndpointDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointDeleterMockRecorder
}

// MockEndpointDeleterMockRecorder is the mock recorder for MockEndpointDeleter.
type MockEndpointDeleterMockRecorder struct {
	mock *MockEndpointDeleter
}

// NewMockEndpointDeleter creates a new mock instance.
func NewMockEndpointDeleter(ctrl *gomock.Controller) *MockEndpointDeleter {
	mock := &MockEndpointDeleter{ctrl: ctrl}
	mock.recorder = &MockEndpointDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointDeleter) EXPECT() *MockEndpointDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockEndpointDeleter) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEndpointDeleterMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEndpointDeleter)(nil).Delete), ctx, id)
}
