// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/events/get.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockEventGetter is a mock of EventGetter interface.
type MockEventGetter struct {
	ctrl     *gomock.Controller
	recorder *MockEventGetterMockRecorder
}

// MockEventGetterMockRecorder is the mock recorder for MockEventGetter.
type MockEventGetterMockRecorder struct {
	mock *MockEventGetter
}

// NewMockEventGetter creates a new mock instance.
func NewMockEventGetter(ctrl *gomock.Controller) *MockEventGetter {
	mock := &MockEventGetter{ctrl: ctrl}
	mock.recorder = &MockEventGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventGetter) EXPECT() *MockEventGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockEventGetter) Get(ctx context.Context, eventID string) (*dto.GetEventResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, eventID)
	ret0, _ := ret[0].(*dto.GetEventResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEventGetterMockRecorder) Get(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEventGetter)(nil).Get), ctx, eventID)
}
