// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/subscriptions/subscribe.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockSubscriptionAdder is a mock of SubscriptionAdder interface.
type MockSubscriptionAdder struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionAdderMockRecorder
}

// MockSubscriptionAdderMockRecorder is the mock recorder for MockSubscriptionAdder.
type MockSubscriptionAdderMockRecorder struct {
	mock *MockSubscriptionAdder
}

// NewMockSubscriptionAdder creates a new mock instance.
func NewMockSubscriptionAdder(ctrl *gomock.Controller) *MockSubscriptionAdder {
	mock := &MockSubscriptionAdder{ctrl: ctrl}
	mock.recorder = &MockSubscriptionAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionAdder) EXPECT() *MockSubscriptionAdderMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockSubscriptionAdder) Add(ctx context.Context, command dto.AddSubscriptionCommand) (*dto.AddSubscriptionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, command)
	ret0, _ := ret[0].(*dto.AddSubscriptionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockSubscriptionAdderMockRecorder) Add(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSubscriptionAdder)(nil).Add), ctx, command)
}
