// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/events/service.go

// Package events is a generated GoMock package.
package events

import (
	context "context"
	reflect "reflect"
	domain "webhook-delivery/internal/domain"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockEventNotifier is a mock of EventNotifier interface.
type MockEventNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockEventNotifierMockRecorder
}

// MockEventNotifierMockRecorder is the mock recorder for MockEventNotifier.
type MockEventNotifierMockRecorder struct {
	mock *MockEventNotifier
}

// NewMockEventNotifier creates a new mock instance.
func NewMockEventNotifier(ctrl *gomock.Controller) *MockEventNotifier {
	mock := &MockEventNotifier{ctrl: ctrl}
	mock.recorder = &MockEventNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventNotifier) EXPECT() *MockEventNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockEventNotifier) Notify() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify")
}

// Notify indicates an expected call of Notify.
func (mr *MockEventNotifierMockRecorder) Notify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockEventNotifier)(nil).Notify))
}

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockEventRepo) Add(ctx context.Context, command dto.PublishEventCommand) (*domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, command)
	ret0, _ := ret[0].(*domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockEventRepoMockRecorder) Add(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockEventRepo)(nil).Add), ctx, command)
}

// GetByID mocks base method.
func (m *MockEventRepo) GetByID(ctx context.Context, id string) (*domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventRepo)(nil).GetByID), ctx, id)
}

// MockDeliveryRepo is a mock of DeliveryRepo interface.
type MockDeliveryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepoMockRecorder
}

// MockDeliveryRepoMockRecorder is the mock recorder for MockDeliveryRepo.
type MockDeliveryRepoMockRecorder struct {
	mock *MockDeliveryRepo
}

// NewMockDeliveryRepo creates a new mock instance.
func NewMockDeliveryRepo(ctrl *gomock.Controller) *MockDeliveryRepo {
	mock := &MockDeliveryRepo{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepo) EXPECT() *MockDeliveryRepoMockRecorder {
	return m.recorder
}

// CreateForEvent mocks base method.
func (m *MockDeliveryRepo) CreateForEvent(ctx context.Context, eventID, eventType string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForEvent", ctx, eventID, eventType)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateForEvent indicates an expected call of CreateForEvent.
func (mr *MockDeliveryRepoMockRecorder) CreateForEvent(ctx, eventID, eventType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForEvent", reflect.TypeOf((*MockDeliveryRepo)(nil).CreateForEvent), ctx, eventID, eventType)
}
