// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/endpoints/get.go

// Package endpoints is a generated GoMock package.
package endpoints

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockEndpointGetter is a mock of EndpointGetter interface.
type MockEndpointGetter struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointGetterMockRecorder
}

// MockEndpointGetterMockRecorder is the mock recorder for MockEndpointGetter.
type MockEndpointGetterMockRecorder struct {
	mock *MockEndpointGetter
}

// NewMockEndpointGetter creates a new mock instance.
func NewMockEndpointGetter(ctrl *gomock.Controller) *MockEndpointGetter {
	mock := &MockEndpointGetter{ctrl: ctrl}
	mock.recorder = &MockEndpointGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointGetter) EXPECT() *MockEndpointGetterMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockEndpointGetter) GetByID(ctx context.Context, id string) (*dto.GetEndpointResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.GetEndpointResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEndpointGetterMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEndpointGetter)(nil).GetByID), ctx, id)
}
