// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/endpoints/get_all.go

// Package endpoints is a generated GoMock package.
package endpoints

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockAllEndpointsGetter is a mock of AllEndpointsGetter interface.
type MockAllEndpointsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockAllEndpointsGetterMockRecorder
}

// MockAllEndpointsGetterMockRecorder is the mock recorder for MockAllEndpointsGetter.
type MockAllEndpointsGetterMockRecorder struct {
	mock *MockAllEndpointsGetter
}

// NewMockAllEndpointsGetter creates a new mock instance.
func NewMockAllEndpointsGetter(ctrl *gomock.Controller) *MockAllEndpointsGetter {
	mock := &MockAllEndpointsGetter{ctrl: ctrl}
	mock.recorder = &MockAllEndpointsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllEndpointsGetter) EXPECT() *MockAllEndpointsGetterMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockAllEndpointsGetter) GetAll(ctx context.Context, command dto.GetAllEndpointsCommand) (*dto.GetAllEndpointsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, command)
	ret0, _ := ret[0].(*dto.GetAllEndpointsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAllEndpointsGetterMockRecorder) GetAll(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAllEndpointsGetter)(nil).GetAll), ctx, command)
}
