// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/endpoints/register.go

// Package endpoints is a generated GoMock package.
package endpoints

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockEndpointRegistrar is a mock of EndpointRegistrar interface.
type MockEndpointRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointRegistrarMockRecorder
}

// MockEndpointRegistrarMockRecorder is the mock recorder for MockEndpointRegistrar.
type MockEndpointRegistrarMockRecorder struct {
	mock *MockEndpointRegistrar
}

// NewMockEndpointRegistrar creates a new mock instance.
func NewMockEndpointRegistrar(ctrl *gomock.Controller) *MockEndpointRegistrar {
	mock := &MockEndpointRegistrar{ctrl: ctrl}
	mock.recorder = &MockEndpointRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointRegistrar) EXPECT() *MockEndpointRegistrarMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockEndpointRegistrar) Register(ctx context.Context, command dto.RegisterEndpointCommand) (*dto.RegisterEndpointResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, command)
	ret0, _ := ret[0].(*dto.RegisterEndpointResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockEndpointRegistrarMockRecorder) Register(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockEndpointRegistrar)(nil).Register), ctx, command)
}
