// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/endpoints/update.go

// Package endpoints is a generated GoMock package.
package endpoints

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockEndpointUpdater is a mock of EndpointUpdater interface.
type MockEndpointUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointUpdaterMockRecorder
}

// MockEndpointUpdaterMockRecorder is the mock recorder for MockEndpointUpdater.
type MockEndpointUpdaterMockRecorder struct {
	mock *MockEndpointUpdater
}

// NewMockEndpointUpdater creates a new mock instance.
func NewMockEndpointUpdater(ctrl *gomock.Controller) *MockEndpointUpdater {
	mock := &MockEndpointUpdater{ctrl: ctrl}
	mock.recorder = &MockEndpointUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointUpdater) EXPECT() *MockEndpointUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockEndpointUpdater) Update(ctx context.Context, command dto.UpdateEndpointCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEndpointUpdaterMockRecorder) Update(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEndpointUpdater)(nil).Update), ctx, command)
}
