version: "3"

vars:
  MIGRATION_DIR: migrations
  DB_URL: postgres://$(DB_USERNAME):$(DB_PASSWORD)@

tasks:
  default:
    desc: "Command list"
    cmds:
      - task --list --color
  mocks:
    desc: "Generating all mocks in project"
    cmds:
      - chmod +x ./scripts/gen_mocks.sh
      - ./scripts/gen_mocks.sh
  test:
    desc: "Run all tests"
    cmds:
      - go test -v -coverprofile=coverage.out ./internal/delivery/... ./internal/services/...
  test:cover:
    desc: "Run all tests with visual coverage out"
    cmds:
      - task test
      - go tool cover -html=coverage.out -o coverage.html
  migrate:up:
    desc: "Migrate up DB"
    cmds:
      - go run ./cmd/migrate/main.go up
  migrate:down:
    desc: "Migrate down DB"
    cmds:
      - go run ./cmd/migrate/main.go down