version: "3"

tasks:
  default:
    desc: "Command list"
    cmds:
      - task --list --color
  mocks:
    desc: "Generating all mocks in project"
    cmds:
      - chmod +x ./scripts/gen_mocks.sh
      - ./scripts/gen_mocks.sh