// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/deliveries/get.go

// Package deliveries is a generated GoMock package.
package deliveries

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockDeliveryGetter is a mock of DeliveryGetter interface.
type MockDeliveryGetter struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryGetterMockRecorder
}

// MockDeliveryGetterMockRecorder is the mock recorder for MockDeliveryGetter.
type MockDeliveryGetterMockRecorder struct {
	mock *MockDeliveryGetter
}

// NewMockDeliveryGetter creates a new mock instance.
func NewMockDeliveryGetter(ctrl *gomock.Controller) *MockDeliveryGetter {
	mock := &MockDeliveryGetter{ctrl: ctrl}
	mock.recorder = &MockDeliveryGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryGetter) EXPECT() *MockDeliveryGetterMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockDeliveryGetter) GetByID(ctx context.Context, id string) (*dto.GetDeliveryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.GetDeliveryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeliveryGetterMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeliveryGetter)(nil).GetByID), ctx, id)
}
