// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/deliveries/get_all.go

// Package deliveries is a generated GoMock package.
package deliveries

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockAllDeliveriesGetter is a mock of AllDeliveriesGetter interface.
type MockAllDeliveriesGetter struct {
	ctrl     *gomock.Controller
	recorder *MockAllDeliveriesGetterMockRecorder
}

// MockAllDeliveriesGetterMockRecorder is the mock recorder for MockAllDeliveriesGetter.
type MockAllDeliveriesGetterMockRecorder struct {
	mock *MockAllDeliveriesGetter
}

// NewMockAllDeliveriesGetter creates a new mock instance.
func NewMockAllDeliveriesGetter(ctrl *gomock.Controller) *MockAllDeliveriesGetter {
	mock := &MockAllDeliveriesGetter{ctrl: ctrl}
	mock.recorder = &MockAllDeliveriesGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllDeliveriesGetter) EXPECT() *MockAllDeliveriesGetterMockRecorder {
	return m.recorder
}

// GetFromEvent mocks base method.
func (m *MockAllDeliveriesGetter) GetFromEvent(ctx context.Context, command dto.GetDeliveriesFromEventCommand) (*dto.GetDeliveriesFromEventResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromEvent", ctx, command)
	ret0, _ := ret[0].(*dto.GetDeliveriesFromEventResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromEvent indicates an expected call of GetFromEvent.
func (mr *MockAllDeliveriesGetterMockRecorder) GetFromEvent(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromEvent", reflect.TypeOf((*MockAllDeliveriesGetter)(nil).GetFromEvent), ctx, command)
}
