// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/deliveries/retry.go

// Package deliveries is a generated GoMock package.
package deliveries

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeliveryRetryer is a mock of DeliveryRetryer interface.
type MockDeliveryRetryer struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRetryerMockRecorder
}

// MockDeliveryRetryerMockRecorder is the mock recorder for MockDeliveryRetryer.
type MockDeliveryRetryerMockRecorder struct {
	mock *MockDeliveryRetryer
}

// NewMockDeliveryRetryer creates a new mock instance.
func NewMockDeliveryRetryer(ctrl *gomock.Controller) *MockDeliveryRetryer {
	mock := &MockDeliveryRetryer{ctrl: ctrl}
	mock.recorder = &MockDeliveryRetryerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRetryer) EXPECT() *MockDeliveryRetryerMockRecorder {
	return m.recorder
}

// Retry mocks base method.
func (m *MockDeliveryRetryer) Retry(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retry", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Retry indicates an expected call of Retry.
func (mr *MockDeliveryRetryerMockRecorder) Retry(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retry", reflect.TypeOf((*MockDeliveryRetryer)(nil).Retry), ctx, id)
}
