// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/subscriptions/service.go

// Package subscriptions is a generated GoMock package.
package subscriptions

import (
	context "context"
	reflect "reflect"
	domain "webhook-delivery/internal/domain"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockSubscriptionRepo is a mock of SubscriptionRepo interface.
type MockSubscriptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepoMockRecorder
}

// MockSubscriptionRepoMockRecorder is the mock recorder for MockSubscriptionRepo.
type MockSubscriptionRepoMockRecorder struct {
	mock *MockSubscriptionRepo
}

// NewMockSubscriptionRepo creates a new mock instance.
func NewMockSubscriptionRepo(ctrl *gomock.Controller) *MockSubscriptionRepo {
	mock := &MockSubscriptionRepo{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepo) EXPECT() *MockSubscriptionRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockSubscriptionRepo) Add(ctx context.Context, command dto.AddSubscriptionCommand) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, command)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockSubscriptionRepoMockRecorder) Add(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSubscriptionRepo)(nil).Add), ctx, command)
}

// Delete mocks base method.
func (m *MockSubscriptionRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionRepo)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockSubscriptionRepo) GetAll(ctx context.Context, endpointID string) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, endpointID)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSubscriptionRepoMockRecorder) GetAll(ctx, endpointID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSubscriptionRepo)(nil).GetAll), ctx, endpointID)
}
