// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/workers/service.go

// Package workers is a generated GoMock package.
package workers

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockDeliveryRepo is a mock of DeliveryRepo interface.
type MockDeliveryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepoMockRecorder
}

// MockDeliveryRepoMockRecorder is the mock recorder for MockDeliveryRepo.
type MockDeliveryRepoMockRecorder struct {
	mock *MockDeliveryRepo
}

// NewMockDeliveryRepo creates a new mock instance.
func NewMockDeliveryRepo(ctrl *gomock.Controller) *MockDeliveryRepo {
	mock := &MockDeliveryRepo{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepo) EXPECT() *MockDeliveryRepoMockRecorder {
	return m.recorder
}

// ClaimPending mocks base method.
func (m *MockDeliveryRepo) ClaimPending(ctx context.Context, batchSize int) ([]dto.ClaimPendingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPending", ctx, batchSize)
	ret0, _ := ret[0].([]dto.ClaimPendingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPending indicates an expected call of ClaimPending.
func (mr *MockDeliveryRepoMockRecorder) ClaimPending(ctx, batchSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPending", reflect.TypeOf((*MockDeliveryRepo)(nil).ClaimPending), ctx, batchSize)
}

// UpdateStatus mocks base method.
func (m *MockDeliveryRepo) UpdateStatus(ctx context.Context, command dto.UpdateDeliveryStatusCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDeliveryRepoMockRecorder) UpdateStatus(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDeliveryRepo)(nil).UpdateStatus), ctx, command)
}
