// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/endpoints/service.go

// Package endpoints is a generated GoMock package.
package endpoints

import (
	context "context"
	reflect "reflect"
	domain "webhook-delivery/internal/domain"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockEndpointRepo is a mock of EndpointRepo interface.
type MockEndpointRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointRepoMockRecorder
}

// MockEndpointRepoMockRecorder is the mock recorder for MockEndpointRepo.
type MockEndpointRepoMockRecorder struct {
	mock *MockEndpointRepo
}

// NewMockEndpointRepo creates a new mock instance.
func NewMockEndpointRepo(ctrl *gomock.Controller) *MockEndpointRepo {
	mock := &MockEndpointRepo{ctrl: ctrl}
	mock.recorder = &MockEndpointRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointRepo) EXPECT() *MockEndpointRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockEndpointRepo) Add(ctx context.Context, command dto.AddEndpointCommand) (*dto.AddEndpointResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, command)
	ret0, _ := ret[0].(*dto.AddEndpointResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockEndpointRepoMockRecorder) Add(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockEndpointRepo)(nil).Add), ctx, command)
}

// Delete mocks base method.
func (m *MockEndpointRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEndpointRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEndpointRepo)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockEndpointRepo) GetAll(ctx context.Context, command dto.GetAllEndpointsCommand) ([]domain.Endpoint, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, command)
	ret0, _ := ret[0].([]domain.Endpoint)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockEndpointRepoMockRecorder) GetAll(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockEndpointRepo)(nil).GetAll), ctx, command)
}

// GetByID mocks base method.
func (m *MockEndpointRepo) GetByID(ctx context.Context, id string) (*domain.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEndpointRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEndpointRepo)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockEndpointRepo) Update(ctx context.Context, command dto.UpdateEndpointCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEndpointRepoMockRecorder) Update(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEndpointRepo)(nil).Update), ctx, command)
}
