// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/subscriptions/delete.go

// Package subscriptions is a generated GoMock package.
package subscriptions

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSubscriptionDeleter is a mock of SubscriptionDeleter interface.
type MockSubscriptionDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionDeleterMockRecorder
}

// MockSubscriptionDeleterMockRecorder is the mock recorder for MockSubscriptionDeleter.
type MockSubscriptionDeleterMockRecorder struct {
	mock *MockSubscriptionDeleter
}

// NewMockSubscriptionDeleter creates a new mock instance.
func NewMockSubscriptionDeleter(ctrl *gomock.Controller) *MockSubscriptionDeleter {
	mock := &MockSubscriptionDeleter{ctrl: ctrl}
	mock.recorder = &MockSubscriptionDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionDeleter) EXPECT() *MockSubscriptionDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSubscriptionDeleter) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionDeleterMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionDeleter)(nil).Delete), ctx, id)
}
