// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/subscriptions/get_all.go

// Package subscriptions is a generated GoMock package.
package subscriptions

import (
	context "context"
	reflect "reflect"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockSubscriptionGetter is a mock of SubscriptionGetter interface.
type MockSubscriptionGetter struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionGetterMockRecorder
}

// MockSubscriptionGetterMockRecorder is the mock recorder for MockSubscriptionGetter.
type MockSubscriptionGetterMockRecorder struct {
	mock *MockSubscriptionGetter
}

// NewMockSubscriptionGetter creates a new mock instance.
func NewMockSubscriptionGetter(ctrl *gomock.Controller) *MockSubscriptionGetter {
	mock := &MockSubscriptionGetter{ctrl: ctrl}
	mock.recorder = &MockSubscriptionGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionGetter) EXPECT() *MockSubscriptionGetterMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockSubscriptionGetter) GetAll(ctx context.Context, endpointID string) ([]dto.GetSubscriptionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, endpointID)
	ret0, _ := ret[0].([]dto.GetSubscriptionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSubscriptionGetterMockRecorder) GetAll(ctx, endpointID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSubscriptionGetter)(nil).GetAll), ctx, endpointID)
}
