// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/deliveries/service.go

// Package deliveries is a generated GoMock package.
package deliveries

import (
	context "context"
	reflect "reflect"
	domain "webhook-delivery/internal/domain"
	dto "webhook-delivery/internal/domain/dto"

	gomock "github.com/golang/mock/gomock"
)

// MockDeliveryRepo is a mock of DeliveryRepo interface.
type MockDeliveryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepoMockRecorder
}

// MockDeliveryRepoMockRecorder is the mock recorder for MockDeliveryRepo.
type MockDeliveryRepoMockRecorder struct {
	mock *MockDeliveryRepo
}

// NewMockDeliveryRepo creates a new mock instance.
func NewMockDeliveryRepo(ctrl *gomock.Controller) *MockDeliveryRepo {
	mock := &MockDeliveryRepo{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepo) EXPECT() *MockDeliveryRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockDeliveryRepo) GetByID(ctx context.Context, id string) (*domain.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeliveryRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeliveryRepo)(nil).GetByID), ctx, id)
}

// GetFromEvent mocks base method.
func (m *MockDeliveryRepo) GetFromEvent(ctx context.Context, eventID string) ([]domain.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromEvent", ctx, eventID)
	ret0, _ := ret[0].([]domain.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromEvent indicates an expected call of GetFromEvent.
func (mr *MockDeliveryRepoMockRecorder) GetFromEvent(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromEvent", reflect.TypeOf((*MockDeliveryRepo)(nil).GetFromEvent), ctx, eventID)
}

// UpdateStatus mocks base method.
func (m *MockDeliveryRepo) UpdateStatus(ctx context.Context, command dto.UpdateDeliveryStatusCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDeliveryRepoMockRecorder) UpdateStatus(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDeliveryRepo)(nil).UpdateStatus), ctx, command)
}
