// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/deliveries/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deliveries"
                ],
                "summary": "Get a delivery by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delivery ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deliveries.GetResponse"
                        }
                    },
                    "400": {
                        "description": "id is not provided",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "delivery not found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/deliveries/{id}/retry": {
            "post": {
                "description": "Resets a delivery to pending and re-queues it for immediate delivery, even if the endpoint is currently inactive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deliveries"
                ],
                "summary": "Retry a delivery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delivery ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "id is not provided",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "delivery not found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/endpoints": {
            "get": {
                "description": "Returns a paginated list of endpoints. Invalid or missing pagination params fall back to defaults.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "endpoints"
                ],
                "summary": "List endpoints",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (from 1, default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (10-100, default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoints.GetAllResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Registers a receiver URL and returns its generated signing secret. The URL is SSRF-validated (loopback / link-local / localhost are rejected).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "endpoints"
                ],
                "summary": "Register a webhook endpoint",
                "parameters": [
                    {
                        "description": "Endpoint to register",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoints.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoints.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "invalid url or malformed body",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/endpoints/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "endpoints"
                ],
                "summary": "Get an endpoint by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoints.GetResponse"
                        }
                    },
                    "400": {
                        "description": "id is not provided",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "endpoint not found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "endpoints"
                ],
                "summary": "Delete an endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "id is not provided",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "endpoint not found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates the URL, active state or description. An empty body is treated as a no-op. If a URL is provided it is SSRF-validated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "endpoints"
                ],
                "summary": "Update an endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update (all optional)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoints.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "id is not provided or invalid url",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "endpoint not found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/endpoints/{id}/subscriptions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "List an endpoint's subscriptions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriptions.GetAllResponse"
                        }
                    },
                    "400": {
                        "description": "id is not provided",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "endpoint not found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds subscriptions for the given event types. Idempotent — event types the endpoint is already subscribed to are ignored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Subscribe an endpoint to event types",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event types to subscribe to",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subscriptions.SubscribeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriptions.SubscribeResponse"
                        }
                    },
                    "400": {
                        "description": "id or event types not provided",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "endpoint not found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "409": {
                        "description": "subscription already exists",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/events": {
            "post": {
                "description": "Publishes an event and fans it out to subscribed endpoints, creating a pending delivery for each. Returns immediately with the number of deliveries created.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Publish an event",
                "parameters": [
                    {
                        "description": "Event to publish",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/events.PublishRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/events.PublishResponse"
                        }
                    },
                    "400": {
                        "description": "event type is empty or malformed body",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get an event by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/events.GetResponse"
                        }
                    },
                    "400": {
                        "description": "id is not provided",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "event not found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/events/{id}/deliveries": {
            "get": {
                "description": "Returns the paginated deliveries created for an event.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deliveries"
                ],
                "summary": "List an event's deliveries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (from 1, default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (10-100, default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deliveries.GetFromEventResponse"
                        }
                    },
                    "400": {
                        "description": "event id is not provided",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Delete a subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "id is not provided",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "subscription not found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "deliveries.DeliveryInfo": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "endpoint_id": {
                    "type": "string",
                    "example": "ep_1a2b3c"
                },
                "event_id": {
                    "type": "string",
                    "example": "ev_1a2b3c"
                },
                "id": {
                    "type": "string",
                    "example": "del_1a2b3c"
                },
                "last_error": {
                    "description": "Error text of the last failed attempt, if any",
                    "type": "string",
                    "example": "HTTP 500"
                },
                "last_response_code": {
                    "description": "Status code of the last delivery attempt, if any",
                    "type": "integer",
                    "example": 500
                },
                "max_attempts": {
                    "type": "integer",
                    "example": 5
                },
                "next_retry_at": {
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "status": {
                    "description": "pending | delivered | failed",
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "deliveries.GetFromEventResponse": {
            "type": "object",
            "properties": {
                "deliveries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/deliveries.DeliveryInfo"
                    }
                },
                "total": {
                    "description": "Total number of deliveries for the event",
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "deliveries.GetResponse": {
            "type": "object",
            "properties": {
                "delivery": {
                    "$ref": "#/definitions/deliveries.DeliveryInfo"
                }
            }
        },
        "endpoints.EndpointInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Billing webhook"
                },
                "event_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "order.created"
                    ]
                },
                "id": {
                    "type": "string",
                    "example": "ep_1a2b3c"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com/webhooks"
                }
            }
        },
        "endpoints.GetAllResponse": {
            "type": "object",
            "properties": {
                "endpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/endpoints.EndpointInfo"
                    }
                },
                "errors": {
                    "description": "Error messages, present only on failure responses",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "invalid url"
                    ]
                },
                "limit": {
                    "description": "Page size",
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "description": "Current page (from 1)",
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "description": "Total number of endpoints",
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "endpoints.GetResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Billing webhook"
                },
                "errors": {
                    "description": "Error messages, present only on failure responses",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "invalid url"
                    ]
                },
                "event_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "order.created"
                    ]
                },
                "id": {
                    "type": "string",
                    "example": "ep_1a2b3c"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com/webhooks"
                }
            }
        },
        "endpoints.RegisterRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "description": {
                    "description": "Optional human-readable description",
                    "type": "string",
                    "example": "Billing webhook"
                },
                "event_types": {
                    "description": "Event types to subscribe to on creation",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "order.created"
                    ]
                },
                "url": {
                    "description": "Receiver URL (http/https, must not be private)",
                    "type": "string",
                    "example": "https://example.com/webhooks"
                }
            }
        },
        "endpoints.RegisterResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "errors": {
                    "description": "Error messages, present only on failure responses",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "invalid url"
                    ]
                },
                "event_types": {
                    "description": "Subscribed event types",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "order.created"
                    ]
                },
                "id": {
                    "description": "Generated endpoint ID",
                    "type": "string",
                    "example": "ep_1a2b3c"
                },
                "is_active": {
                    "description": "Whether the endpoint is active",
                    "type": "boolean",
                    "example": true
                },
                "secret": {
                    "description": "Signing secret (returned once, on creation)",
                    "type": "string",
                    "example": "whsec_3f9a1c2e8d"
                },
                "url": {
                    "description": "Receiver URL",
                    "type": "string",
                    "example": "https://example.com/webhooks"
                }
            }
        },
        "endpoints.UpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "New description",
                    "type": "string",
                    "example": "Billing webhook"
                },
                "is_active": {
                    "description": "Pause or resume the endpoint",
                    "type": "boolean",
                    "example": false
                },
                "url": {
                    "description": "New receiver URL (SSRF-validated if present)",
                    "type": "string",
                    "example": "https://example.com/webhooks"
                }
            }
        },
        "events.GetResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "ev_1a2b3c"
                },
                "payload": {
                    "type": "object"
                },
                "type": {
                    "type": "string",
                    "example": "order.created"
                }
            }
        },
        "events.PublishRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "payload": {
                    "description": "Arbitrary JSON payload delivered to subscribers",
                    "type": "object"
                },
                "type": {
                    "description": "Event type",
                    "type": "string",
                    "example": "order.created"
                }
            }
        },
        "events.PublishResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "deliveries_created": {
                    "description": "Number of pending deliveries created for subscribers",
                    "type": "integer",
                    "example": 3
                },
                "errors": {
                    "description": "Error messages, present only on failure responses",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "invalid url"
                    ]
                },
                "id": {
                    "type": "string",
                    "example": "ev_1a2b3c"
                },
                "type": {
                    "type": "string",
                    "example": "order.created"
                }
            }
        },
        "subscriptions.GetAllResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "Error messages, present only on failure responses",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "invalid url"
                    ]
                },
                "subscriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/subscriptions.SubscriptionInfo"
                    }
                }
            }
        },
        "subscriptions.SubscribeRequest": {
            "type": "object",
            "required": [
                "event_types"
            ],
            "properties": {
                "event_types": {
                    "description": "Event types to subscribe the endpoint to",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "order.created"
                    ]
                }
            }
        },
        "subscriptions.SubscribeResponse": {
            "type": "object",
            "properties": {
                "endpoint_id": {
                    "type": "string",
                    "example": "ep_1a2b3c"
                },
                "errors": {
                    "description": "Error messages, present only on failure responses",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "invalid url"
                    ]
                },
                "subscriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/subscriptions.SubscriptionInfo"
                    }
                }
            }
        },
        "subscriptions.SubscriptionInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-07-01T12:00:00Z"
                },
                "endpoint_id": {
                    "type": "string",
                    "example": "ep_1a2b3c"
                },
                "event_type": {
                    "type": "string",
                    "example": "order.created"
                },
                "id": {
                    "type": "string",
                    "example": "sub_1a2b3c"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "Error messages, present only on failure responses",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "invalid url"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Webhook Delivery",
	Description:      "An open-source webhook delivery service in Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
